# Autorzy: Sebastian Lyszkowski, Marek Bobrowski
index:
    path: /
    controller: App\Controller\HomePageController::index
registration:
    path: /register
    controller: App\Controller\RegistrationPageController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
search:
    path: /search
    controller: App\Controller\SearchGameController::index
searchresults:
    path: /searchresults
    controller: App\Controller\SearchGameController::search
addgame:
    path: /addgame
    controller: App\Controller\AddGameController::index
rategame:
    path: /rategame
    controller: App\Controller\RateGameController::index
changepage:
    path: /changepage
    controller: App\Controller\SearchGameController::changePage
userlist:
    path: /userlist
    controller: App\Controller\UserManagementController::index
deleteuser:
    path: /deleteuser
    controller: App\Controller\UserManagementController::delete
searchuser:
    path: /searchuser
    controller: App\Controller\UserManagementController::search
changepageuserlist:
    path: /changepageuserlist
    controller: App\Controller\UserManagementController::changePage
changepageuser:
    path: /changepageuser
    controller: App\Controller\UserManagementController::changePageUser
news:
    path: /news
    controller: App\Controller\NewsController::index
addpost:
    path: /addpost
    controller: App\Controller\AddPostController::index
searchpost:
    path: /searchpost
    controller: App\Controller\NewsController::search
deletepost:
    path: /deletepost
    controller: App\Controller\NewsController::delete
changepagenews:
    path: /changepagenews
    controller: App\Controller\NewsController::changePage
changepagepost:
    path: /changepagepost
    controller: App\Controller\NewsController::changePagePost
ban:
    path: /ban
    controller: App\Controller\BanController::index
unban:
    path: /unban
    controller: App\Controller\UnbanController::index