# Autor: Sebastian Lyszkowski
index:
    path: /
    controller: App\Controller\HomePageController::index
registration:
    path: /register
    controller: App\Controller\RegistrationPageController::index
login:
    path: /login
    controller: App\Controller\LoginPageController::index
search:
    path: /search
    controller: App\Controller\SearchGameController::index
searchresults:
    path: /searchresults
    controller: App\Controller\SearchGameController::search
addgame:
    path: /addgame
    controller: App\Controller\AddGameController::index
rategame:
    path: /rategame
    controller: App\Controller\RateGameController::index