# Autor: Marek Bobrowski -----------------------------------------------------------------------------------------------
index:
    path: /
    controller: App\Controller\HomePageController::index

registration:
    path: /register
    controller: App\Controller\RegistrationPageController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

ban:
    path: /ban
    controller: App\Controller\BanController::ban
unban:
    path: /unban
    controller: App\Controller\BanController::unban
# ----------------------------------------------------------------------------------------------------------------------
# Autor: Sebastian Łyszkowski ------------------------------------------------------------------------------------------
search_game:
    path: /search
    controller: App\Controller\SearchGameController::index
search_game_results:
    path: /searchresults
    controller: App\Controller\SearchGameController::search
change_page_game:
    path: /changepage
    controller: App\Controller\SearchGameController::changePage

add_game:
    path: /addgame
    controller: App\Controller\AddGameController::index

rate_game:
    path: /rategame
    controller: App\Controller\RateGameController::index


userlist:
    path: /userlist
    controller: App\Controller\UserManagementController::index
delete_user:
    path: /deleteuser
    controller: App\Controller\UserManagementController::delete
search_user:
    path: /searchuser
    controller: App\Controller\UserManagementController::search
change_page_userlist:
    path: /changepageuserlist
    controller: App\Controller\UserManagementController::changePage
change_page_user:
    path: /changepageuser
    controller: App\Controller\UserManagementController::changePageUser

news:
    path: /news
    controller: App\Controller\NewsController::index
search_post:
    path: /searchpost
    controller: App\Controller\NewsController::search
delete_post:
    path: /deletepost
    controller: App\Controller\NewsController::delete
change_page_news:
    path: /changepagenews
    controller: App\Controller\NewsController::changePage
change_page_post:
    path: /changepagepost
    controller: App\Controller\NewsController::changePagePost

add_post:
    path: /addpost
    controller: App\Controller\AddPostController::index
# ----------------------------------------------------------------------------------------------------------------------
